### PR TITLE
fix analytics endpoints

### LINKED ISSUE #190: Analytics request responses fail to parse to JSON
Analytics endpoints are currently failing as postgres is returing java date time objects instead of strings for dates.

This will need to be changed such that the returned dates are parsed into strings before returning as json.

### PR DESCRIPTION
**Pull request by toasted226**
- removed deprecated validation calls in analytics endpoints
- added function in analytics core to automatically convert all instances of java.time.LocalDate to string using postwalk
- fixed bug in user type validation authorisation preventing analytics endpoints from being authorised
- updated postman collection to remove old local tokens and added analytics endpoints to it

### CODE REVIEW

File: src/source/routes/analytics/creator/top.clj [hunk 1]
```diff
@@ -33,25 +32,19 @@
...
+                     (analytics/top-statistics-query ds mindate maxdate n top-field)
+                     (mapv (fn [result]
+                             (set/rename-keys result {top-field :top}))))
+        ids (mapv :top results)
+        names (record-names ds top-field ids)
+        juxted (->> names
+                    (mapv (juxt :id :name))
+                    (into {}))
+        named-results (mapv (fn [{:keys [top] :as r}]
+                              (assoc r :top (clojure.core/get juxted top (str top))))
```
Comment (merveillevaneck) [inline src/source/routes/analytics/creator/top.clj:48]: this could be `(mapv #(assoc ....) results)` this could also just be put inside the thread-last that juxted uses. then you dont need to make a juxted variable:

```
(->> (names)
       (mapv ...)
       (into {})
       (mapv #(assoc ....)))
```

**Review by merveillevaneck — APPROVED** [review]
