### PR TITLE
congest integration

### LINKED ISSUE #4: add feed api
for this one you have to wait for the rss parser to be complete. But this ticket will go as follows:
- set up endpoint to upload url as string along with content type
- we can get the user from the token in the request so that will be part of context
- from there you need to send the url entered to our parser which will return some data. 
- you can then write this data to the db in the appropriate places (may need some extra service functions if they don't already exist)

### LINKED ISSUE #18: integrate congest into source
@KaidanTheron you know what to do here

### LINKED ISSUE #77: Update exception middleware to log out errors
The reitit exception middleware by default does not log out the exception when it is caught, it only returns a 500 response with a brief description of the error. This middleware is customisable, so it should be improved to also log out exceptions when they occur.

### PR DESCRIPTION
**Pull request by toasted226**
Integrated Congest into Source. There is now a Job Scheduler that can be used from within Source itself and by admins. Scheduled jobs are persisted in sqlite and are recoverable at server startup or by admins. The sqlite tables store the job's status, metadata, args and handler identifiers.

In addition, feeds routes have been added to view all feeds, and to allow a creator to add a new feed. Adding a new feed creates a feed record, extracts RSS feed data and creates an incoming post, then schedules a job to update both the feed and the post every 24 hours.

### CODE REVIEW

File: src/source/jobs/oplog.clj [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+                  :auto-start (b->i (:auto-start job-metadata))
+                  :stop-after-fail (b->i (:stop-after-fail job-metadata))
+                  :kill-after (:kill-after job-metadata)
+                  :num-calls (:num-calls job-metadata)
+                  :interval (:interval job-metadata)
+                  :recurring (b->i (:recurring? job-metadata))
+                  :created-at (:created-at job-metadata)
+                  :sleep (b->i (:sleep job-metadata))}
+        job (services/job ds {:id id})
+        metadata-id (when-not (some? job)
```
Comment (merveillevaneck) [inline src/source/jobs/oplog.clj]: these all need to be given docstrings that explainds the scope of each function

File: src/source/jobs/oplog.clj [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    (= action "start")
+    (update-job! metadata "running")
+
+    (or (= action "stop") (= action "kill"))
+    (update-job! metadata "stopped")
+
+    (= action "run")
+    (do
+      (update-job! metadata "running")
+      (update-job-metadata! metadata))))
```
Comment (merveillevaneck) [inline src/source/jobs/oplog.clj]: please add a docstring to show what this function is meant for

File: src/source/middleware/core.clj [hunk 3]
```diff
@@ -22,10 +23,33 @@
...
+
+(defn apply-ds [app ds]
+  (-> app
+      (wrap-ds ds)))
+
 (defn apply-store [app store]
   (-> app
       (wrap-store store)))
 
+(defn apply-js [app js]
```
Comment (merveillevaneck) [inline src/source/middleware/core.clj]: DOCSTRING, js is very ambiguous in the context of web

**Review by merveillevaneck — APPROVED** [review]
please update the persistance layer to only do what it needs to do. instead of makign extensions for the methods in the congest service. we need at most maybe 3 functions, and only 1 of them really needs to be called by the top level, which should be wherever the server is started (a.k.a. a component)

File: src/source/server.clj [hunk 4]
```diff
@@ -1,26 +1,52 @@
...
+            [source.jobs.core :as jobs]
+            [source.routes.interface :as routes]
+            [source.util :as util]))
 
 (defonce ^:private *server (atom nil))
 
+(defonce ^:private *components (atom nil))
+
+(defn initialise-components! []
+  (if (some? @*components)
```
Comment (merveillevaneck) [inline src/source/server.clj]: replace this with a `some` fn invocation where the predicate is true if the component is marked as truthy. this way, you can call a function to determine if the components are on or off. you can then also add dependencies to any component, which should result in the component being "off" if all its dependencies or some of its depencies are "off".

**Review by merveillevaneck — APPROVED** [review]

File: src/source/server.clj [hunk 5]
```diff
@@ -1,38 +1,103 @@
...
 
 (defn stop-server []
   (println "Stopping server...")
-  (when (some? @*server)
-    (@*server))
-  (reset! *server nil))
+  (when (some? (:js @*components))
+    (congest/kill! (:js @*components)))
+  (when (some? (:server @*components))
+    (let [server (:server @*components)]
```
Comment (merveillevaneck) [inline src/source/server.clj]: call this server symbol stop-server! instead

**Review by merveillevaneck — APPROVED** [review]
make a cleanup ticket for the PR review discussions and get this merged in in the meantime. good work!
